// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Car Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CAR: add a car', async function() {
    await driver.get("https://qauto2.forstudy.space/panel/garage")
    await driver.manage().window().setRect({ width: 1289, height: 996 })
    await driver.findElement(By.css(".btn-primary")).click()
    {
      const element = await driver.findElement(By.css(".btn-primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("addCarMileage")).sendKeys("1")
    await driver.findElement(By.id("addCarMileage")).click()
    await driver.findElement(By.id("addCarMileage")).sendKeys("2")
    await driver.findElement(By.id("addCarMileage")).click()
    {
      const element = await driver.findElement(By.id("addCarMileage"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("addCarMileage")).sendKeys("3")
    await driver.findElement(By.id("addCarMileage")).click()
    await driver.findElement(By.id("addCarMileage")).sendKeys("4")
    await driver.findElement(By.id("addCarMileage")).click()
    await driver.findElement(By.id("addCarMileage")).sendKeys("5")
    await driver.findElement(By.id("addCarMileage")).click()
    await driver.findElement(By.id("addCarMileage")).sendKeys("6")
    await driver.findElement(By.id("addCarMileage")).click()
    await driver.findElement(By.id("addCarMileage")).sendKeys("7")
    await driver.findElement(By.id("addCarMileage")).click()
    await driver.findElement(By.id("addCarMileage")).sendKeys("8")
    await driver.findElement(By.id("addCarMileage")).click()
    {
      const element = await driver.findElement(By.id("addCarMileage"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("addCarMileage")).sendKeys("9")
    await driver.findElement(By.id("addCarMileage")).click()
    await driver.findElement(By.id("addCarMileage")).sendKeys("10")
    await driver.findElement(By.id("addCarMileage")).click()
    await driver.findElement(By.css(".modal-footer > .btn-primary")).click()
  })
  it('CAR: change expenses', async function() {
    await driver.get("https://qauto2.forstudy.space/panel/garage")
    await driver.manage().window().setRect({ width: 1289, height: 996 })
    await driver.findElement(By.css(".car_add-expense")).click()
    await driver.findElement(By.id("addExpenseMileage")).click()
    await driver.findElement(By.id("addExpenseMileage")).sendKeys("11")
    await driver.findElement(By.id("addExpenseMileage")).click()
    await driver.findElement(By.id("addExpenseMileage")).sendKeys("12")
    await driver.findElement(By.id("addExpenseMileage")).click()
    await driver.findElement(By.id("addExpenseMileage")).sendKeys("13")
    await driver.findElement(By.id("addExpenseMileage")).click()
    await driver.findElement(By.id("addExpenseMileage")).sendKeys("14")
    await driver.findElement(By.id("addExpenseMileage")).click()
    await driver.findElement(By.id("addExpenseMileage")).sendKeys("15")
    await driver.findElement(By.id("addExpenseMileage")).click()
    {
      const element = await driver.findElement(By.id("addExpenseMileage"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("addExpenseLiters")).click()
    await driver.findElement(By.id("addExpenseLiters")).sendKeys("2")
    await driver.findElement(By.id("addExpenseTotalCost")).click()
    await driver.findElement(By.id("addExpenseTotalCost")).sendKeys("2")
    await driver.findElement(By.css(".modal-footer > .btn-primary")).click()
  })
})
