// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('User Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('USER: register new user', async function() {
    await driver.get("https://qauto2.forstudy.space/")
    await driver.manage().window().setRect({ width: 1289, height: 996 })
    await driver.findElement(By.css(".hero-descriptor_btn")).click()
    await driver.findElement(By.id("signupName")).click()
    await driver.findElement(By.id("signupName")).sendKeys("Firstname")
    await driver.findElement(By.id("signupLastName")).click()
    await driver.findElement(By.id("signupLastName")).sendKeys("Lastname")
    await driver.findElement(By.id("signupEmail")).click()
    await driver.findElement(By.id("signupEmail")).sendKeys("testtest@email.com")
    await driver.findElement(By.id("signupPassword")).click()
    await driver.findElement(By.id("signupPassword")).sendKeys("Aa123456")
    await driver.findElement(By.id("signupRepeatPassword")).click()
    await driver.findElement(By.id("signupRepeatPassword")).sendKeys("Aa123456")
    await driver.findElement(By.css(".btn-primary:nth-child(1)")).click()
    await driver.findElement(By.linkText("Log out")).click()
  })
  it('USER: check user name on the Profile page after registration', async function() {
    await driver.get("https://qauto2.forstudy.space/")
    await driver.manage().window().setRect({ width: 1289, height: 996 })
    await driver.findElement(By.css(".btn-outline-white")).click()
    await driver.findElement(By.id("signinEmail")).click()
    await driver.findElement(By.id("signinEmail")).sendKeys("testtest@email.com")
    await driver.findElement(By.id("signinPassword")).click()
    await driver.findElement(By.id("signinPassword")).sendKeys("Aa123456")
    await driver.findElement(By.css(".btn-primary:nth-child(2)")).click()
    await driver.findElement(By.linkText("Profile")).click()
    {
      const elements = await driver.findElements(By.css(".profile_name"))
      assert(elements.length)
    }
    assert(await driver.findElement(By.css(".profile_name")).getText() == "Firstname Lastname")
    await driver.findElement(By.linkText("Log out")).click()
  })
  it('USER: delete account', async function() {
    await driver.get("https://qauto2.forstudy.space/")
    await driver.manage().window().setRect({ width: 1289, height: 996 })
    await driver.findElement(By.css(".btn-outline-white")).click()
    await driver.findElement(By.id("signinEmail")).click()
    await driver.findElement(By.id("signinEmail")).sendKeys("testtest@email.com")
    await driver.findElement(By.id("signinPassword")).click()
    await driver.findElement(By.id("signinPassword")).sendKeys("Aa123456")
    await driver.findElement(By.css(".btn-primary:nth-child(2)")).click()
    await driver.findElement(By.linkText("Settings")).click()
    await driver.findElement(By.css(".btn-danger-bg")).click()
    await driver.findElement(By.css(".btn-danger")).click()
    await driver.close()
  })
})
